name: Anton Rudeshko
description: Web dev and digital art.
url: http://www.rudeshko.com

markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true

timezone: Europe/Moscow
encoding: UTF-8
paginate: 5
paginate_path: "/:num"

contacts:
    twitter: AntonRudeshko
    gplus: AntonRudeshko
    github: anton-rudeshko
    email: anton@rudeshko.com

prose:
    siteurl: http://www.rudeshko.com
    media: assets

gems:
- jekyll-paginate
- jekyll-feed
- jemoji
