name: Anton Rudeshko
description: Web dev and digital art.
url: http://anton-rudeshko.github.io

markdown: redcarpet
pygments: true

timezone: Europe/Moscow
encoding: UTF-8

contacts:
    twitter: 404tesla
    github: anton-rudeshko
