name: Anton Rudeshko
description: Web dev and digital art.
url: http://new.rudeshko.com

markdown: redcarpet
pygments: true

timezone: Europe/Moscow
encoding: UTF-8

contacts:
    twitter: AntonRudeshko
    gplus: AntonRudeshko
    github: anton-rudeshko
    email: anton@rudeshko.com

prose:
    siteurl: http://new.rudeshko.com
    media: assets
