name: Anton Rudeshko
description: Web dev and digital art.
url: http://new.rudeshko.com

markdown: redcarpet
pygments: true

timezone: Europe/Moscow
encoding: UTF-8

contacts:
    email: anton@rudeshko.com
    twitter: AntonRudeshko
    github: anton-rudeshko

prose:
	siteurl: http://new.rudeshko.com
    media: assets
