name: Anton Rudeshko
description: Web dev and digital art.
url: http://www.rudeshko.com

markdown: redcarpet
redcarpet:
  extensions: ["strikethrough"]
highlighter: pygments

timezone: Europe/Moscow
encoding: UTF-8
paginate: 5
paginate_path: "/:num"

contacts:
    twitter: AntonRudeshko
    gplus: AntonRudeshko
    github: anton-rudeshko
    email: anton@rudeshko.com

prose:
    siteurl: http://www.rudeshko.com
    media: assets
